# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b509dd6f2676998bcc17d483a0746a7296c8f4506b88137b0ee26ade626960603877b52863b6041d84ca07ace5f1c7366ebb9f4f1c9ac721ad226ccbc9fea61b

test:
  secret_key_base: 05bdf6b495cfefa0633daa9d502bec03cc109d62caee1f054028faeb504a5ef01db05344f85a2fe0c5e4af7e2f6e2175e31218908818c13f28f783aa2a9e1647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
